name: tpi-rag
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - poppler
  - pillow
  - tesseract
  - ipykernel
  - pip:
      - python-dotenv
      - google-genai
      - pdf2image
      - "unstructured[pdf]"
      - unstructured-inference
      - onnxruntime
      - python-magic-bin
      - nltk
      - "openai>=1.0"
      - sqlite-vec
      - rank-bm25 
      - numpy 
      - ruff>=0.7,<1.0
      - pytest 