name: tpi-rag
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - poppler
  - pillow
  - tesseract
  - pip:
      - python-dotenv
      - google-genai
      - pdf2image
      - "unstructured[pdf]"
      - unstructured-inference
      - onnxruntime
      - python-magic-bin